---
id: speee-cafe-meetup-02
base_name: want-to-increase-oss-developers
tags:
- rabbit
- oss
- speee
presentation_date: 2016-09-01
version: 2016.9.1.0
licenses:
- CC BY-SA 4.0
slideshare_id: speee-cafe-meetup-02
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: 須藤功平
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
